# Generated by Django 3.1 on 2020-12-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_finish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
