# Generated by Django 3.1 on 2020-12-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_sheet_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='product_name',
            new_name='product_finish',
        ),
    ]
