# Generated by Django 3.1 on 2020-12-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201208_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='product_finish',
            new_name='finish',
        ),
    ]
