# Generated by Django 3.1 on 2020-12-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201208_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='finish',
        ),
    ]
