# Generated by Django 3.1 on 2020-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_sheet_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vsg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
