# Generated by Django 3.1 on 2020-12-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_is_vsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_vsg',
        ),
    ]
