# Generated by Django 3.1 on 2020-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201218_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_paginate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
