# Generated by Django 3.1 on 2020-12-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_is_paginate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
