# Generated by Django 3.1 on 2020-12-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201219_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='main_finish',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='sub_finish',
        ),
    ]
