# Generated by Django 3.1 on 2020-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20201219_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='main_finish',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sub_finish',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
