# Generated by Django 3.1 on 2020-12-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='phone',
        ),
    ]
