# Generated by Django 3.1 on 2020-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20201217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue_page',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/pages/self.index'),
        ),
    ]
