# Generated by Django 3.1 on 2020-12-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20201218_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue_page',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/pages'),
        ),
    ]
