# Generated by Django 3.1 on 2020-12-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20201218_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue_page',
            old_name='index',
            new_name='index_1',
        ),
        migrations.RenameField(
            model_name='catalogue_page',
            old_name='main_image',
            new_name='main_image_1',
        ),
        migrations.AddField(
            model_name='catalogue_page',
            name='index_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogue_page',
            name='main_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/pages'),
        ),
    ]
