# Generated by Django 3.1 on 2020-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20201218_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue_page',
            old_name='index_1',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='catalogue_page',
            old_name='index_2',
            new_name='page_first',
        ),
        migrations.AddField(
            model_name='catalogue_page',
            name='page_second',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
