# Generated by Django 3.1 on 2020-12-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20201218_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='main_image',
            new_name='main_image_1',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='main_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue'),
        ),
    ]
