# Generated by Django 3.1 on 2020-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20201218_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='page_first',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='page_second',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
