# Generated by Django 3.1 on 2020-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20201218_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='page_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='page_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
