# Generated by Django 3.1 on 2020-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20201219_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='name_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
