# Generated by Django 3.1 on 2020-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('page_name', models.CharField(blank=True, max_length=100, null=True)),
                ('page_info', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
