# Generated by Django 3.1 on 2020-12-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informative_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('page_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='informative')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='informative')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='informative')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='informative')),
                ('side', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Looper_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.page_handler')),
            ],
        ),
        migrations.CreateModel(
            name='Looper_Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='looper')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='looper')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='looper')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='looper')),
                ('side', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.looper_section')),
            ],
        ),
    ]
